[[project]]
    name = "This Website"
    desc = "The very website you are looking at is available on Github!"
    tags = ["webdev"]
    links = [
        { name = "Github", url = "https://github.com/TeaDrinkingProgrammer/TeaDrinkingProgrammer.github.io" },
        { name = "Blogpost", url = "../blog/how-to-make-your-blog-blazingly-fast"}
    ]